file: /modules/security-authorization
description: |
  Authorization in MongoDB
---
file: /modules/security-authentication
description: |
  Authentication in MongoDB
---
file: /exercises/secure-mongod
description: |
  Lab on standing up a mongod with authorization enabled
---
file: /modules/security-encryption
description: |
  Encryption at rest in MongoDB
---
file: /exercises/secured-replicaset
description: |
  Using keyfiles to secure a replica set
...
