git:
  remote:
    upstream: 'mongodb/docs-training'
    tools: 'mongodb/docs-tools'
project:
  name: 'training'
  tag: 'training'
  url: 'http://docs.mongodb.org/training'
  title: 'MongoDB Training'
  branched: false
  editions:
    - name: instructor
      tag: training-instructor
    - name: student
      tag: training-student
version:
  release: '2.6.0'
  branch: '2.6'
system:
  make:
    generated:
      - 'integration'
      - 'meta'
      - 'push'
      - 'sphinx'
    static:
      - 'makefile.compatibility'
      - 'makefile.clean'
      - 'makefile.dtf'
  tools:
    pinned: false
    ref: HEAD
  files:
    - 'pdfs.yaml'
    - 'intersphinx.yaml'
    - 'push.yaml'
paths:
  output: 'build'
  source: 'source'
  includes: 'source/includes'
  images: 'source/images'
  tools: 'bin'
  buildsystem: 'build/docs-tools'
  builddata: 'config'
  locale: 'locale'
...