fr:
  inherit: base
es:
  inherit: base
ja:
  inherit: base
zh:
  inherit: base
it:
  inherit: base
base:
  targets:
    - 'dirhtml-instructor'
    - 'dirhtml-student'
    - 'html-instructor'
    - 'html-student'
    - 'latex-instructor'
    - 'latex-student'
    - 'singlehtml-instructor'
    - 'singlehtml-student'
    - 'slides-instructor'
    - 'slides-student'
    # - 'epub-instructor'
    # - 'epub-student'
    # - 'json-instructor'
    # - 'json-student'
  doc-root: []
  branch-root: null
...