source: 'contents'
output: 'training.tex'
title: 'MongoDB Training, Instructor Guide'
author: 'MongoDB, Inc.'
class: 'howto'
tag: 'manual'
edition: 'instructor'
---
source: 'contents'
output: 'training.tex'
title: 'MongoDB Training'
author: 'MongoDB, Inc.'
class: 'howto'
tag: 'manual'
edition: 'student'
---
source: 'meta/one-day-fundamentals'
output: 'one-day-fundamentals.tex'
title: 'MongoDB Fundamentals Workshop, Instructor Guide'
author: 'MongoDB, Inc.'
class: 'howto'
tag: 'workbook'
edition: 'instructor'
---
source: 'meta/one-day-fundamentals'
output: 'one-day-fundamentals.tex'
title: 'MongoDB Fundamentals Workshop'
author: 'MongoDB, Inc.'
class: 'howto'
tag: 'workbook'
edition: 'student'
...
