# source: 'contents'
# output: 'training.tex'
# title: 'MongoDB Training, Instructor Guide'
# author: 'MongoDB, Inc.'
# class: 'howto'
# tag: 'manual'
# edition: 'instructor'
# ---
# source: 'contents'
# output: 'training.tex'
# title: 'MongoDB Training'
# author: 'MongoDB, Inc.'
# class: 'howto'
# tag: 'manual'
# edition: 'student'
# ---
# source: 'meta/one-day-fundamentals'
# output: 'one-day-fundamentals.tex'
# title: 'MongoDB Fundamentals Workshop, Instructor Guide'
# author: 'MongoDB, Inc.'
# class: 'howto'
# tag: 'workbook'
# edition: 'instructor'
# ---
# source: 'meta/one-day-fundamentals'
# output: 'one-day-fundamentals.tex'
# title: 'MongoDB Fundamentals Workshop'
# author: 'MongoDB, Inc.'
# class: 'howto'
# tag: 'workbook'
# edition: 'student'
# ---
source: 'meta/admin-three-day'
output: 'admin-three-day-instructor.tex'
title: 'MongoDB Administrator Training'
author: 'MongoDB, Inc.'
class: 'howto'
tag: 'guide'
edition: 'instructor'
---
source: 'meta/admin-three-day'
output: 'admin-three-day-student.tex'
title: 'MongoDB Administrator Training'
author: 'MongoDB, Inc.'
class: 'howto'
tag: 'workbook'
edition: 'student'
---
source: 'meta/developer-three-day'
output: 'developer-three-day-instructor.tex'
title: 'MongoDB Developer Training'
author: 'MongoDB, Inc.'
class: 'howto'
tag: 'guide'
edition: 'instructor'
---
source: 'meta/developer-three-day'
output: 'developer-three-day-student.tex'
title: 'MongoDB Developer Training'
author: 'MongoDB, Inc.'
class: 'howto'
tag: 'workbook'
edition: 'student'
---
source: 'meta/developer-rapid-start'
output: 'developer-rapid-start-instructor.tex'
title: "MongoDB Developer Rapid Start Training"
author: 'MongoDB, Inc.'
class: 'howto'
tag: 'guide'
edition: 'instructor'
---
source: 'meta/developer-rapid-start'
output: 'developer-rapid-start-student.tex'
title: "MongoDB Developer Rapid Start Training"
author: 'MongoDB, Inc.'
class: 'howto'
tag: 'workbook'
edition: 'student'
---
source: 'meta/ops-rapid-start'
output: 'ops-rapid-start-instructor.tex'
title: "MongoDB Operations Rapid Start Training"
author: 'MongoDB, Inc.'
class: 'howto'
tag: 'guide'
edition: 'instructor'
---
source: 'meta/ops-rapid-start'
output: 'ops-rapid-start-student.tex'
title: "MongoDB Operations Rapid Start Training"
author: 'MongoDB, Inc.'
class: 'howto'
tag: 'workbook'
edition: 'student'
---
source: 'meta/essentials-four-day'
output: 'essentials-four-day-instructor.tex'
title: 'MongoDB Essentials Training'
author: 'MongoDB, Inc.'
class: 'howto'
tag: 'guide'
edition: 'instructor'
---
source: 'meta/essentials-four-day'
output: 'essentials-four-day-student.tex'
title: 'MongoDB Essentials Training'
author: 'MongoDB, Inc.'
class: 'howto'
tag: 'workbook'
edition: 'student'
---
source: 'meta/data-modeling-workshop'
output: 'data-modeling-workshop.tex'
title: 'MongoDB Data Modeling Workshop'
author: 'MongoDB, Inc.'
class: 'howto'
tag: 'workbook'
edition: 'student'
---
source: 'meta/data-modeling-workshop'
output: 'data-modeling-workshop.tex'
title: 'MongoDB Data Modeling Workshop'
author: 'MongoDB, Inc.'
class: 'howto'
tag: 'guide'
edition: 'instructor'
---
source: 'meta/opsmanager-workshop'
output: 'opsmanager-workshop.tex'
title: 'MongoDB Ops Manager Workshop'
author: 'MongoDB, Inc.'
class: 'howto'
tag: 'workbook'
edition: 'student'
---
source: 'meta/opsmanager-workshop'
output: 'opsmanager-workshop.tex'
title: 'MongoDB Ops Manager Workshop'
author: 'MongoDB, Inc.'
class: 'howto'
tag: 'guide'
edition: 'instructor'
---
source: 'meta/advanced-developer'
output: 'advanced-developer-student.tex'
title: 'MongoDB Advanced Developer Training'
author: 'MongoDB, Inc.'
class: 'howto'
tag: 'workbook'
edition: 'student'
---
# source: 'meta/advanced-developer'
# output: 'advanced-developer-instructor.tex'
# title: 'MongoDB Advanced Developer Training'
# author: 'MongoDB, Inc.'
# class: 'howto'
# tag: 'guide'
# edition: 'instructor'
# source: 'meta/five-day-training'
# output: 'five-day-training-student.tex'
# title: 'MongoDB Five-Day Training'
# author: 'MongoDB, Inc.'
# class: 'howto'
# tag: 'workbook'
# edition: 'student'
# ---
# source: 'meta/adm-half-day'
# output: 'adm-half-day-instructor.tex'
# title: 'Advanced Data Modeling Workshop'
# author: 'MongoDB, Inc.'
# class: 'howto'
# tag: 'guide'
# edition: 'instructor'
# ---
# source: 'meta/adm-half-day'
# output: 'adm-half-day-student.tex'
# title: 'Advanced Data Modeling Workshop'
# author: 'MongoDB, Inc.'
# class: 'howto'
# tag: 'guide'
# edition: 'student'
# ---
source: 'meta/advanced-administrator'
output: 'advanced-administrator-instructor.tex'
title: "MongoDB Advanced Administrator Training"
author: 'MongoDB, Inc.'
class: 'howto'
tag: 'guide'
edition: 'instructor'
---
source: 'meta/advanced-administrator'
output: 'advanced-administrator-student.tex'
title: "MongoDB Advanced Administrator Training"
author: 'MongoDB, Inc.'
class: 'howto'
tag: 'workbook'
edition: 'student'
---
source: 'meta/train-the-trainer'
output: 'train-the-trainer.tex'
title: "MongoDB Train The Trainer"
author: 'MongoDB, Inc.'
class: 'howto'
tag: 'workbook'
edition: 'student'
---
#source: 'meta/nhtt-atlas-cloudmanager-opsmanager'
#output: 'nhtt-atlas-cloudmanager-opsmanager.tex'
#title: 'MongoDB NHTT Atlas, Cloud Manager and Ops Manager'
#author: 'MongoDB, Inc.'
#class: 'howto'
#tag: 'workbook'
#edition: 'internal'
#---
source: 'meta/nhtt-company'
output: 'nhtt-company-student.tex'
title: 'MongoDB NHTT Company'
author: 'MongoDB, Inc.'
class: 'howto'
tag: 'workbook'
edition: 'internal'
---
source: 'meta/nhtt-schema-design'
output: 'nhtt-schema-design-student.tex'
title: 'MongoDB NHTT Schema Design'
author: 'MongoDB, Inc.'
class: 'howto'
tag: 'workbook'
edition: 'internal'
---
source: 'meta/nhtt-security'
output: 'nhtt-security-student.tex'
title: 'MongoDB NHTT Security'
author: 'MongoDB, Inc.'
class: 'howto'
tag: 'workbook'
edition: 'internal'
---
source: 'meta/nhtt-storage-engines'
output: 'nhtt-storage-engines-student.tex'
title: 'MongoDB NHTT Storage Engines'
author: 'MongoDB, Inc.'
class: 'howto'
tag: 'workbook'
edition: 'internal'
---
source: 'meta/security-workshop'
output: 'security-workshop-student.tex'
title: 'MongoDB Security Workshop'
author: 'MongoDB, Inc.'
class: 'howto'
tag: 'workbook'
edition: 'student'
---
source: 'meta/security-workshop'
output: 'security-workshop-instructor.tex'
title: 'MongoDB Security Workshop'
author: 'MongoDB, Inc.'
class: 'howto'
tag: 'guide'
edition: 'instructor'
#---
#source: 'meta/nhtt-tools'
#output: 'nhtt-tools.tex'
#title: 'MongoDB NHTT Tools'
#author: 'MongoDB, Inc.'
#class: 'howto'
#tag: 'workbook'
#edition: 'internal'
...
