source: 'contents'
output: 'training.tex'
title: 'MongoDB Training, Instructor Guide'
author: 'MongoDB, Inc.'
class: 'howto'
tag: 'manual'
edition: 'instructor'
---
source: 'contents'
output: 'training.tex'
title: 'MongoDB Training'
author: 'MongoDB, Inc.'
class: 'howto'
tag: 'manual'
edition: 'student'
---
source: 'meta/one-day-fundamentals'
output: 'one-day-fundamentals.tex'
title: 'MongoDB Fundamentals Workshop, Instructor Guide'
author: 'MongoDB, Inc.'
class: 'howto'
tag: 'workbook'
edition: 'instructor'
---
source: 'meta/one-day-fundamentals'
output: 'one-day-fundamentals.tex'
title: 'MongoDB Fundamentals Workshop'
author: 'MongoDB, Inc.'
class: 'howto'
tag: 'workbook'
edition: 'student'
---
source: 'meta/admin'
output: 'admin-instructor.tex'
title: 'MongoDB Administrators Training'
author: 'MongoDB, Inc.'
class: 'howto'
tag: 'guide'
edition: 'instructor'
---
source: 'meta/admin'
output: 'admin-student.tex'
title: 'MongoDB Administrators Training'
author: 'MongoDB, Inc.'
class: 'howto'
tag: 'workbook'
edition: 'student'
---
source: 'meta/developer'
output: 'developer-instructor.tex'
title: 'MongoDB Developers Training'
author: 'MongoDB, Inc.'
class: 'howto'
tag: 'guide'
edition: 'instructor'
---
source: 'meta/developer'
output: 'developer-student.tex'
title: 'MongoDB Developers Training'
author: 'MongoDB, Inc.'
class: 'howto'
tag: 'workbook'
edition: 'student'
---
source: 'meta/essentials'
output: 'essentials-instructor.tex'
title: 'MongoDB Essentials Training'
author: 'MongoDB, Inc.'
class: 'howto'
tag: 'guide'
edition: 'instructor'
---
source: 'meta/essentials'
output: 'essentials-student.tex'
title: 'MongoDB Essentials Training'
author: 'MongoDB, Inc.'
class: 'howto'
tag: 'workbook'
edition: 'student'
...
