# source: 'contents'
# output: 'training.tex'
# title: 'MongoDB Training, Instructor Guide'
# author: 'MongoDB, Inc.'
# class: 'howto'
# tag: 'manual'
# edition: 'instructor'
# ---
# source: 'contents'
# output: 'training.tex'
# title: 'MongoDB Training'
# author: 'MongoDB, Inc.'
# class: 'howto'
# tag: 'manual'
# edition: 'student'
# ---
# source: 'meta/one-day-fundamentals'
# output: 'one-day-fundamentals.tex'
# title: 'MongoDB Fundamentals Workshop, Instructor Guide'
# author: 'MongoDB, Inc.'
# class: 'howto'
# tag: 'workbook'
# edition: 'instructor'
# ---
# source: 'meta/one-day-fundamentals'
# output: 'one-day-fundamentals.tex'
# title: 'MongoDB Fundamentals Workshop'
# author: 'MongoDB, Inc.'
# class: 'howto'
# tag: 'workbook'
# edition: 'student'
# ---
source: 'meta/admin-three-day'
output: 'admin-three-day-instructor.tex'
title: 'MongoDB Administrator Training'
author: 'MongoDB, Inc.'
class: 'howto'
tag: 'guide'
edition: 'instructor'
---
source: 'meta/admin-three-day'
output: 'admin-three-day-student.tex'
title: 'MongoDB Administrator Training'
author: 'MongoDB, Inc.'
class: 'howto'
tag: 'workbook'
edition: 'student'
---
# source: 'meta/admin-two-day'
# output: 'admin-two-day-instructor.tex'
# title: 'MongoDB Administrator Training'
# author: 'MongoDB, Inc.'
# class: 'howto'
# tag: 'guide'
# edition: 'instructor'
# ---
# source: 'meta/admin-two-day'
# output: 'admin-two-day-student.tex'
# title: 'MongoDB Administrator Training'
# author: 'MongoDB, Inc.'
# class: 'howto'
# tag: 'workbook'
# edition: 'student'
# ---
# source: 'meta/admin-one-day'
# output: 'admin-one-day-instructor.tex'
# title: 'MongoDB Administrator Fundamentals'
# author: 'MongoDB, Inc.'
# class: 'howto'
# tag: 'guide'
# edition: 'instructor'
# ---
# source: 'meta/admin-one-day'
# output: 'admin-one-day-student.tex'
# title: 'MongoDB Administrator Fundamentals'
# author: 'MongoDB, Inc.'
# class: 'howto'
# tag: 'workbook'
# edition: 'student'
# ---
source: 'meta/developer-three-day'
output: 'developer-three-day-instructor.tex'
title: 'MongoDB Developer Training'
author: 'MongoDB, Inc.'
class: 'howto'
tag: 'guide'
edition: 'instructor'
---
source: 'meta/developer-three-day'
output: 'developer-three-day-student.tex'
title: 'MongoDB Developer Training'
author: 'MongoDB, Inc.'
class: 'howto'
tag: 'workbook'
edition: 'student'
---
# source: 'meta/developer-two-day'
# output: 'developer-two-day-instructor.tex'
# title: 'MongoDB Developer Training'
# author: 'MongoDB, Inc.'
# class: 'howto'
# tag: 'guide'
# edition: 'instructor'
# ---
# source: 'meta/developer-two-day'
# output: 'developer-two-day-student.tex'
# title: 'MongoDB Developer Training'
# author: 'MongoDB, Inc.'
# class: 'howto'
# tag: 'workbook'
# edition: 'student'
# ---
source: 'meta/cap1-two-day'
output: 'cap1-two-day-instructor.tex'
title: 'MongoDB Developer Training'
author: 'MongoDB, Inc.'
class: 'howto'
tag: 'guide'
edition: 'instructor'
---
source: 'meta/cap1-two-day'
output: 'cap1-two-day-student.tex'
title: 'MongoDB Developer Training'
author: 'MongoDB, Inc.'
class: 'howto'
tag: 'workbook'
edition: 'student'
---
source: 'meta/cap1-three-day'
output: 'cap1-three-day-instructor.tex'
title: 'MongoDB Essentials Training'
author: 'MongoDB, Inc.'
class: 'howto'
tag: 'guide'
edition: 'instructor'
---
source: 'meta/cap1-three-day'
output: 'cap1-three-day-student.tex'
title: 'MongoDB Essentials Training'
author: 'MongoDB, Inc.'
class: 'howto'
tag: 'workbook'
edition: 'student'
---
source: 'meta/rapid-start'
output: 'rapid-start-instructor.tex'
title: 'MongoDB Rapid Start Training'
author: 'MongoDB, Inc.'
class: 'howto'
tag: 'guide'
edition: 'instructor'
---
source: 'meta/rapid-start'
output: 'rapid-start-student.tex'
title: 'MongoDB Rapid Start Training'
author: 'MongoDB, Inc.'
class: 'howto'
tag: 'workbook'
edition: 'student'
---
# source: 'meta/developer-one-day'
# output: 'developer-one-day-instructor.tex'
# title: 'MongoDB Developer Fundamentals'
# author: 'MongoDB, Inc.'
# class: 'howto'
# tag: 'guide'
# edition: 'instructor'
# ---
# source: 'meta/developer-one-day'
# output: 'developer-one-day-student.tex'
# title: 'MongoDB Developer Fundamentals'
# author: 'MongoDB, Inc.'
# class: 'howto'
# tag: 'workbook'
# edition: 'student'
#---
source: 'meta/essentials-four-day'
output: 'essentials-four-day-instructor.tex'
title: 'MongoDB Essentials Training'
author: 'MongoDB, Inc.'
class: 'howto'
tag: 'guide'
edition: 'instructor'
---
source: 'meta/essentials-four-day'
output: 'essentials-four-day-student.tex'
title: 'MongoDB Essentials Training'
author: 'MongoDB, Inc.'
class: 'howto'
tag: 'workbook'
edition: 'student'
---
# source: 'meta/essentials-three-day'
# output: 'essentials-three-day-instructor.tex'
# title: 'MongoDB Essentials Training'
# author: 'MongoDB, Inc.'
# class: 'howto'
# tag: 'guide'
# edition: 'instructor'
# ---
# source: 'meta/essentials-three-day'
# output: 'essentials-three-day-student.tex'
# title: 'MongoDB Essentials Training'
# author: 'MongoDB, Inc.'
# class: 'howto'
# tag: 'workbook'
# edition: 'student'
# ---
source: 'meta/advanced-developer'
output: 'advanced-developer-student.tex'
title: 'MongoDB Advanced Developer Training'
author: 'MongoDB, Inc.'
class: 'howto'
tag: 'workbook'
edition: 'student'
---
source: 'meta/advanced-developer'
output: 'advanced-developer-instructor.tex'
title: 'MongoDB Advanced Developer Training'
author: 'MongoDB, Inc.'
class: 'howto'
tag: 'guide'
edition: 'instructor'
# source: 'meta/five-day-training'
# output: 'five-day-training-student.tex'
# title: 'MongoDB Five-Day Training'
# author: 'MongoDB, Inc.'
# class: 'howto'
# tag: 'workbook'
# edition: 'student'
# ---
# source: 'meta/adm-half-day'
# output: 'adm-half-day-instructor.tex'
# title: 'Advanced Data Modeling Workshop'
# author: 'MongoDB, Inc.'
# class: 'howto'
# tag: 'guide'
# edition: 'instructor'
# ---
# source: 'meta/adm-half-day'
# output: 'adm-half-day-student.tex'
# title: 'Advanced Data Modeling Workshop'
# author: 'MongoDB, Inc.'
# class: 'howto'
# tag: 'guide'
# edition: 'student'
...
