target: push-student
paths:
  remote: /data/sites/training
  local: public/student
  static: [ ]
options: [ 'recursive' ]
env: publication
dependency: push-if-up-to-date
---
target: push-instructor
paths:
  remote: /data/sites/training
  local: public/instructor
  static: [ ]
options: [ 'recursive' ]
env: publication
dependency: push-if-up-to-date
---
target: stage-student
paths:
  remote: /srv/public/test/training/student
  local: public/student
  static: [ ]
options: [ 'recursive' ]
env: staging
dependency: stage-if-up-to-date
---
target: stage-instructor
paths:
  remote: /srv/public/test/training/instructor
  local: public/instructor
  static: [ ]
options: [ 'recursive' ]
env: staging
dependency: stage-if-up-to-date
...
