# The items in the ``builders`` list are the name of Sphinx builders
# supported by ``sphinx-build``.
#
# The ``prerequsites`` list stores all targets that must build before
# sphinx can begin.
#
# The ``generated-source`` list stores all the targets that generate rst.

prerequisites:
  - setup
  - generate-source
sphinx_builders:
  - 'dirhtml'
  - 'singlehtml'
  - 'html'
  - 'latex'
  - 'epub'
  - 'json'
  - 'slides'
generated-source:
  - tables
  - toc
  - intersphinx
  - images
editions:
  - 'instructor'
  - 'student'
## --- ##
dirhtml-student:
  inherit: student-web-base
html-student:
  inherit: student-web-base
latex-student:
  inherit: student-web-base
epub-student:
  inherit: student-web-base
singlehtml-student:
  inherit: student-web-base
linkcheck-student:
  inherit: student-web-base
gettext-student:
  inherit: student-web-base
json-student:
  inherit: student-web-base
slides-student:
  inherit: student-web-base
## --- ##
slides-instructor:
  inherit: instructor-web-base
dirhtml-instructor:
  inherit: instructor-web-base
html-instructor:
  inherit: instructor-web-base
latex-instructor:
  inherit: instructor-web-base
epub-instructor:
  inherit: instructor-web-base
singlehtml-instructor:
  inherit: instructor-web-base
linkcheck-instructor:
  inherit: instructor-web-base
gettext-instructor:
  inherit: instructor-web-base
json-instructor:
  inherit: instructor-web-base
## --- ##
student-web-base:
  inherit: student-base
  tags:
    - web
    - website
    - student
  excluded_files:
    - 'meta/introduction.txt'
student-print-base:
  inherit: student-base
  tags:
    - print
    - student
instructor-web-base:
  inherit: instructor-base
  tags:
    - web
    - website
    - instructor
  excluded_files:
    - 'meta/introduction.txt'
instructor-print-base:
  inherit: instructor-base
  tags:
    - print
    - instructor
## --- ##
instructor-base:
  edition: 'instructor'
  excluded_files: []
student-base:
  edition: 'student'
  excluded_files: []
...