# The items in the ``builders`` list are the name of Sphinx builders
# supported by ``sphinx-build``.
#
# The ``prerequsites`` list stores all targets that must build before
# sphinx can begin.
#
# The ``generated-source`` list stores all the targets that generate rst.

prerequisites:
  - setup
  - generate-source
sphinx_builders:
  - 'dirhtml'
  - 'singlehtml'
  - 'html'
  - 'latex'
  - 'epub'
  - 'json'
  - 'slides'
generated-source:
  - tables
  - toc
  - intersphinx
  - images
editions:
  - 'instructor'
  - 'student'
  - 'internal'
## --- ##
dirhtml-student:
  inherit: student-web-base
html-student:
  inherit: student-web-base
latex-student:
  inherit: student-print-base
  tags:
    - offset
epub-student:
  inherit: student-print-base
singlehtml-student:
  inherit: student-web-base
linkcheck-student:
  inherit: student-web-base
gettext-student:
  inherit: student-web-base
json-student:
  inherit: student-web-base
slides-student:
  inherit: student-web-base
## --- ##
slides-instructor:
  inherit: instructor-web-base
dirhtml-instructor:
  inherit: instructor-web-base
html-instructor:
  inherit: instructor-web-base
latex-instructor:
  inherit: instructor-print-base
  tags:
    - offset
epub-instructor:
  inherit: instructor-print-base
singlehtml-instructor:
  inherit: instructor-web-base
linkcheck-instructor:
  inherit: instructor-web-base
gettext-instructor:
  inherit: instructor-web-base
json-instructor:
  inherit: instructor-web-base
## --- ##
slides-internal:
  inherit: internal-web-base
dirhtml-internal:
  inherit: internal-web-base
html-internal:
  inherit: internal-web-base
latex-internal:
  inherit: internal-print-base
  tags:
    - offset
epub-internal:
  inherit: internal-print-base
singlehtml-internal:
  inherit: internal-web-base
linkcheck-internal:
  inherit: internal-web-base
gettext-internal:
  inherit: internal-web-base
json-internal:
  inherit: internal-web-base
## --- ##
student-web-base:
  inherit: student-base
  tags:
    - web
    - website
    - student
  excluded:
    - /meta/introduction.txt
student-print-base:
  inherit: student-base
  tags:
    - print
    - student
instructor-web-base:
  inherit: instructor-base
  tags:
    - web
    - website
    - instructor
  excluded:
    - /meta/one-day-fundamentals.txt
instructor-print-base:
  inherit: instructor-base
  tags:
    - print
    - instructor
internal-web-base:
  inherit: internal-base
  tags:
    - web
    - website
    - instructor
    - internal
internal-print-base:
  inherit: internal-base
  tags:
    - print
    - instructor
    - internal
## --- ##
instructor-base:
  edition: 'instructor'
  excluded:
    - /modules/internal
    - /scripts
student-base:
  edition: 'student'
  excluded:
    - /modules/internal
    - /scripts
internal-base:
  edition: 'internal'
  excluded:
    - /scripts
...