project: 'mongodb-training'
master_doc: 'contents'
logo: "themes/training/static/mongodb_logo.png"
paths:
  static: ['source/.static']
theme:
  name: 'training'
  project: 'training'
  google_analytics: 'UA-000000000'
  book_path_base: 'MongoDB-training'
  repo: 'docs'
  jira: 'EDU'
  sitename: 'MongoDB University'
  nav_excluded: []
sidebars:
  '**':
    - 'pagenav.html'
...