source_dir: build/docs-mongodb/source
sources: 
  - images/crud-write-concern-ack.svg
  - images/crud-write-concern-unack.svg
  - images/crud-write-concern-w2.svg
  - images/replica-set-trigger-election.svg
  - images/replica-set-read-write-operations-primary.svg
  - images/sharded-collection.svg
  - images/sharding-splitting.png
  - images/does_scale.png
  - images/doesnt_scale.png
...
