#!/usr/bin/env bash

# Bash script for provisioning the LDAP server

set -e
set -x

function config_network(){
  export CLIENT_IP_ADDR=`ifconfig | grep 'inet addr:'| grep -v '127.0.0.1' | cut -d: -f2 | awk '{ print $1}' | tail -1`
  export CLIENT_FQDN=`hostname`
  export CLIENT_NAME=`hostname | cut -d. -f 1 | tr '[:upper:]' '[:lower:]'`
  echo "Configuring /etc/hosts ..."
  echo "127.0.0.1 localhost localhost.localdomain localhost4 localhost4.localdomain4" > /etc/hosts
  echo "::1       localhost localhost.localdomain localhost6 localhost6.localdomain6" >> /etc/hosts
  echo "$CLIENT_IP_ADDR    $CLIENT_FQDN $CLIENT_NAME" >> /etc/hosts

  service iptables stop
  chkconfig iptables off
}

function install_openldap(){
  echo "Install Dependencies"
  yum -y install openldap-servers openldap-clients openldap-devel openldap python-devel gcc cyrus-sasl-plain xfsprogs net-snmp ps-misc wget curl
  echo "Instal pip"
  curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
  python get-pip.py
  easy_install pip
  pip -V
  pip install python-ldap
  rm get-pip.py
}

function config_ldap(){
  cd /vagrant
  chmod +x setup-ldap.sh
  ./setup-ldap.sh
}

config_network
install_openldap
config_ldap

echo "DONE"
